[project]
name = "data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.74",
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
data-pipeline = "data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
